### ISSUE TITLE
`LPUSH` and `RPOP` prints errors

### ISSUE THREAD

**Issue by mcdappdev** [vapor/redis#132] opened 2018-12-03 20:33 UTC
`conn.lpush([data], into: key)` prints `[WARNING] [Async] [QueueHandler] Read triggered when input queue was empty, ignoring: RedisData(storage: Redis.RedisData.Storage.integer(1)).`

`conn.rpop(key)` prints `[WARNING] [Async] [QueueHandler] Read triggered when input queue was empty, ignoring: RedisData(storage: Redis.RedisData.Storage.bulkString(125 bytes)).`

**Comment by vzsg** [comment] 2019-01-02 22:36
Is this still a thing? Because I can't seem to be able to reproduce it in a test.

**Comment by mcdappdev** [comment] 2019-01-02 22:37
Maybe it's just how I was doing it, you can see the implementation here: https://github.com/vapor-community/redis-jobs/blob/master/Sources/RedisJobs/RedisJobs.swift#L45

**Comment by tanner0101** [comment] 2019-02-07 20:58
This was resolved in https://github.com/vapor/redis/releases/tag/3.0.3

**Closed by tanner0101** 2019-02-07 20:58 UTC
